cogsci2020_draft2:	cogsci2020_draft2.tex 
	pdflatex cogsci2020_draft2.tex  
	bibtex cogsci2020_draft2
	pdflatex cogsci2020_draft2.tex  
	pdflatex cogsci2020_draft2.tex  

cogsci2020_draft1:	cogsci2020_draft1.tex 
	pdflatex cogsci2020_draft1.tex  
	bibtex cogsci2020_draft1
	pdflatex cogsci2020_draft1.tex  
	pdflatex cogsci2020_draft1.tex  
